import { REQUEST } from '@nestjs/core';

export const EVENT_LISTENER_METADATA = 'EVENT_LISTENER_METADATA';
export const NET_EVENT_LISTENER_METADATA = 'NET_EVENT_LISTENER_METADATA';
export const EVENT_PAYLOAD = REQUEST;
