name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: [test, release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx nx affected --target=publish --parallel=3 --all --ver=${{ github.ref }} --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
